"""Coverage / confidence report for the compiled database (``python -m racingsim data report``)."""

from __future__ import annotations

import json
import sqlite3
from collections import Counter
from datetime import date


def _count(conn, sql: str) -> int:
    return conn.execute(sql).fetchone()[0] or 0


def _has(conn, table: str) -> bool:
    return conn.execute("SELECT 1 FROM sqlite_master WHERE name = ?", (table,)).fetchone() is not None


def summary(conn: sqlite3.Connection) -> dict:
    s: dict = {}
    s["series_profiles"] = _count(conn, "SELECT COUNT(*) FROM series_info")
    s["sanctioning_bodies"] = _count(conn, "SELECT COUNT(*) FROM sanctioning_body")
    s["car_classes"] = _count(conn, "SELECT COUNT(*) FROM car_class")
    s["career_paths"] = _count(conn, "SELECT COUNT(*) FROM career_path")
    s["career_path_steps"] = _count(conn, "SELECT COUNT(*) FROM career_path_step")
    s["career_stages"] = _count(conn, "SELECT COUNT(*) FROM career_stage")
    s["transitions"] = _count(conn, "SELECT COUNT(*) FROM transition")
    s["advancement_factors"] = _count(conn, "SELECT COUNT(*) FROM advancement_factor")
    s["ranged_facts"] = _count(conn, "SELECT COUNT(*) FROM fact")
    s["sources"] = _count(conn, "SELECT COUNT(*) FROM source")
    s["ledger_entries"] = _count(conn, "SELECT COUNT(*) FROM ledger")
    s["sources_unavailable"] = _count(conn, "SELECT COUNT(*) FROM source_unavailable")
    s["datasets_evaluated"] = _count(conn, "SELECT COUNT(*) FROM dataset")
    s["tracks"] = _count(conn, "SELECT COUNT(*) FROM track_facts")
    s["history_series"] = _count(conn, "SELECT COUNT(DISTINCT source) FROM season")
    s["history_seasons"] = _count(conn, "SELECT COUNT(*) FROM season")
    s["history_races"] = _count(conn, "SELECT COUNT(*) FROM race")
    s["history_standings_rows"] = _count(conn, "SELECT COUNT(*) FROM standing")
    s["race_results_rows"] = _count(conn, "SELECT COUNT(*) FROM race_result") if _has(conn, "race_result") else 0
    s["race_results_races"] = _count(conn, "SELECT COUNT(*) FROM race_info") if _has(conn, "race_info") else 0
    s["historical_drivers"] = _count(conn, "SELECT COUNT(*) FROM driver")
    s["historical_team_seasons"] = _count(conn, "SELECT COUNT(*) FROM team")
    s["historical_teams"] = _count(conn, "SELECT COUNT(DISTINCT team) FROM team")
    return s


def confidence_by_category(conn) -> dict[str, Counter]:
    out: dict[str, Counter] = {}
    for table, label in (("series_info", "series"), ("sanctioning_body", "sanctioning bodies"),
                         ("car_class", "car classes"), ("career_path", "career paths"),
                         ("career_stage", "career stages"), ("advancement_factor", "advancement factors")):
        out[label] = Counter(r[0] or "unrated" for r in conn.execute(f"SELECT confidence FROM {table}"))
    out["transitions"] = Counter(r[0] or "unrated" for r in conn.execute("SELECT confidence FROM transition"))
    out["ranged facts"] = Counter(r[0] or "unrated" for r in conn.execute("SELECT confidence FROM fact"))
    return out


def gaps(conn) -> list[str]:
    out = []
    for attr, label in (("annual_cost_usd", "annual cost"), ("typical_age", "typical age"),
                        ("field_size", "field size"), ("horsepower", "horsepower")):
        n = _count(conn, f"SELECT COUNT(*) FROM series_info s WHERE NOT EXISTS (SELECT 1 FROM fact f "
                         f"WHERE f.entity_id = s.id AND (f.attribute = '{attr}' OR f.attribute LIKE '%.{attr}'))")
        if n:
            out.append(f"{n} series profiles have no {label} fact")
    n = _count(conn, "SELECT COUNT(*) FROM season WHERE data_level = 'champion_only'")
    if n:
        out.append(f"{n} historical seasons have only the champion (no schedule/standings)")
    n = _count(conn, "SELECT COUNT(*) FROM race WHERE cancelled = 0 AND track_id IS NULL")
    if n:
        out.append(f"{n} historical races are not matched to a track in the database")
    return out


def markdown(conn) -> str:
    s = summary(conn)
    lines = [f"# Data report ({date.today().isoformat()})", "",
             "Generated by `python -m racingsim data report` from `data/racingsim.db`.", "",
             "## Contents", "", "| Item | Count |", "|---|---|"]
    lines += [f"| {k.replace('_', ' ')} | {v:,} |" for k, v in s.items()]
    lines += ["", "## Confidence by category", "", "| Category | high | medium | low | unrated |", "|---|---|---|---|---|"]
    for cat, c in confidence_by_category(conn).items():
        lines.append(f"| {cat} | {c.get('high', 0)} | {c.get('medium', 0)} | {c.get('low', 0)} | {c.get('unrated', 0)} |")
    lines += ["", "## Historical seasons by series", "", "| Series (source) | Seasons | Years | Races | Data level |",
              "|---|---|---|---|---|"]
    for src, n, lo, hi in conn.execute("SELECT source, COUNT(*), MIN(year), MAX(year) FROM season GROUP BY source "
                                       "ORDER BY source"):
        races = _count(conn, f"SELECT COUNT(*) FROM race WHERE source = '{src}'")
        levels = Counter(r[0] or "full" for r in conn.execute("SELECT data_level FROM season WHERE source = ?", (src,)))
        lines.append(f"| {src} | {n} | {lo}–{hi} | {races:,} | {', '.join(f'{k} {v}' for k, v in levels.items())} |")
    lines += ["", "## Sources by kind", "", "| Kind | Sources |", "|---|---|"]
    for kind, n in conn.execute("SELECT COALESCE(kind,'?'), COUNT(*) FROM source GROUP BY kind ORDER BY 2 DESC"):
        lines.append(f"| {kind} | {n} |")
    unavailable = conn.execute("SELECT source, url, reason, replacement_source FROM source_unavailable").fetchall()
    if unavailable:
        lines += ["", "## Sources skipped (access restricted)", "", "| Source | Reason | Replacement |", "|---|---|---|"]
        seen = set()
        for src, url, reason, repl in unavailable:
            if (src, reason) in seen:
                continue
            seen.add((src, reason))
            lines.append(f"| {src} ({url or ''}) | {reason} | {repl or ''} |")
    g = gaps(conn)
    if g:
        lines += ["", "## Known gaps", ""] + [f"* {x}" for x in g]
    return "\n".join(lines) + "\n"


def tracks_by(conn, column: str) -> Counter:
    return Counter(r[0] for r in conn.execute(f"SELECT {column} FROM track_facts"))


def dumps(conn) -> str:
    return json.dumps(summary(conn), indent=1)
