"""Declarative configuration: which Wikipedia pages / sections feed which series and events."""

YEAR_MIN, YEAR_MAX = 1995, 2026

# champion source kinds:
#   ("table", page, heading_regex, driver_label_regex)   -> extract.year_winner_tables
#   ("list", page, heading_regex)                        -> extract.list_winners(list_section(...))
SERIES = {
    "woo_sprint": dict(name="World of Outlaws Sprint Car Series", discipline="sprint_car", level="national",
                       champ=("table", "World of Outlaws", r"Past champions", r"driver"),
                       season_re=r"^(\d{4}) World of Outlaws.*Sprint Car", venues_tpl="Template:World of Outlaws Sprint Car Series race venues"),
    "woo_late_model": dict(name="World of Outlaws Late Model Series", discipline="dirt_late_model", level="national",
                           champ=("table", "World of Outlaws Late Model Series", r"Past champions", r"driver"),
                           season_re=r"^(\d{4}) World of Outlaws.*Late Model", extra_years=(1988, 1989),
                           venues_tpl="Template:World of Outlaws Late Model Series race venues"),
    "lolmds": dict(name="Lucas Oil Late Model Dirt Series", discipline="dirt_late_model", level="national",
                   champ=("list", "Lucas Oil Late Model Dirt Series", r"Past champions"),
                   season_re=r"^(\d{4}) Lucas Oil Late Model Dirt Series", venues_tpl="Template:Lucas Oil Late Model Dirt Series race venues", mrp="lolmds"),
    "usac_sprint": dict(name="USAC National Sprint Car Championship", discipline="sprint_car", level="national",
                        champ=("table", "United States Auto Club", r"Active series / USAC National Sprint Car Championship$", r"driver"),
                        season_re=r"^(\d{4}) USAC.*Sprint Car"),
    "usac_midget": dict(name="USAC National Midget Championship", discipline="midget", level="national",
                        champ=("table", "United States Auto Club", r"Active series / USAC National Midget Championship$", r"driver"),
                        season_re=r"^(\d{4}) USAC.*Midget", venues_tpl="Template:USAC National Midget Series race venues"),
    "usac_silver_crown": dict(name="USAC Silver Crown Series", discipline="silver_crown", level="national",
                              champ=("table", "United States Auto Club", r"Active series / USAC Silver Crown Series$", r"driver"),
                              season_re=r"^(\d{4}) USAC.*Silver Crown", venues_tpl="Template:USAC Silver Crown race venues"),
    "usac_cra_sprint": dict(name="USAC/CRA Sprint Car Series", discipline="sprint_car", level="regional",
                            champ=("table", "United States Auto Club", r"Active series / USAC/CRA Sprint Car Series$", r"driver"),
                            season_re=r"^(\d{4}) USAC/CRA", venues_tpl="Template:USAC/CRA Sprint Car Series race venues"),
    "usac_western_midget": dict(name="USAC Western States Midget Series", discipline="midget", level="regional",
                                champ=("table", "United States Auto Club", r"Active series / USAC Western States Midget Series$", r"driver"),
                                season_re=r"^(\d{4}) USAC Western"),
    "all_stars": dict(name="All Star Circuit of Champions", discipline="sprint_car", level="super_regional",
                      champ=("table", "All Star Circuit of Champions", r"Champions", r"driver"),
                      season_re=r"^(\d{4}) All Star Circuit"),
    "high_limit": dict(name="High Limit Racing", discipline="sprint_car", level="national",
                       champ=("table", "High Limit Racing", r"^Champions", r"winning driver"),
                       season_re=r"^(\d{4}) High Limit", mrp="high_limit"),
    "super_dirtcar": dict(name="Super DIRTcar Series", discipline="dirt_modified", level="super_regional",
                          champ=("table", "Super DIRTcar Series", r"Champions by year", r"super dirtcar series"),
                          season_re=r"^(\d{4}) Super DIRTcar"),
    "dirtcar_358": dict(name="DIRTcar 358 Modified Series", discipline="dirt_modified", level="regional",
                        champ=("table", "Super DIRTcar Series", r"Champions by year", r"dirtcar 358 modified series"),
                        season_re=r"^(\d{4}) DIRTcar 358"),
    "powri_midget": dict(name="POWRi National Midget League", discipline="midget", level="national",
                         champ=("list", "POWRi Midget Racing", r"^POWRi National Midget League$", 1),
                         season_re=r"^(\d{4}) POWRi"),
    "powri_west_midget": dict(name="POWRi West Midget League", discipline="midget", level="regional",
                              champ=("list", "POWRi Midget Racing", r"^POWRi West Midget League$"), season_re=None),
    "busch_all_star_tour": dict(name="Busch All-Star Tour", discipline="dirt_late_model", level="super_regional",
                                champ=("table", "Busch All-Star Tour", r"List of series champions", r"champion"), season_re=None),
    "supr": dict(name="Southern United Professional Racing", discipline="dirt_late_model", level="regional",
                 champ=("list", "Southern United Professional Racing", r"Series champions"), season_re=None,
                 caveat="Wikipedia list does not state the class; SUPR runs late models (and sprints); treated as late-model title."),
    "national_sprint_tour": dict(name="National Sprint Tour", discipline="sprint_car", level="national",
                                 champ=("list", "National Sprint Tour", r"^Champion"), season_re=None),
    # ---- series without Wikipedia coverage: champion lists from official sites (robots.txt checked, see official.py)
    "usmts": dict(name="United States Modified Touring Series (USMTS)", discipline="dirt_modified", level="national",
                  champ=("official", "usmts"), season_re=None, mrp="usmts"),
    "ascs_national": dict(name="American Sprint Car Series (ASCS) National Tour", discipline="sprint_car", level="national",
                          champ=("official", "ascs"), season_re=None),
    "stss": dict(name="Short Track Super Series (overall / Elite title)", discipline="dirt_modified", level="super_regional",
                 champ=("official", "stss"), season_re=None, mrp="stss"),
    "stss_north": dict(name="Short Track Super Series North Region", discipline="dirt_modified", level="regional",
                       champ=("official", "stss_north"), season_re=None),
    "stss_south": dict(name="Short Track Super Series South Region", discipline="dirt_modified", level="regional",
                       champ=("official", "stss_south"), season_re=None),
    "mars_late_model": dict(name="MARS Late Model Championship", discipline="dirt_late_model", level="regional",
                            champ=("official", "mars_late_model"), season_re=None, mrp="mars_late_model",
                            caveat="2017 had separate East/West champions on the official list; no single 2017 champion recorded."),
    "mars_modified": dict(name="MARS Modified Championship", discipline="dirt_modified", level="regional",
                          champ=("official", "mars_modified"), season_re=None),
}

# Crown-jewel events. src kinds as above; meta gives fixed venue facts (only when the article ties the event to one track).
EVENTS = {
    "knoxville_nationals": dict(name="Knoxville Nationals", discipline="sprint_car", src=("table", "Knoxville Nationals", r"^Past winners / Knoxville Nationals Winners$", r"driver"),
                                track="Knoxville Raceway"),
    "knoxville_360_nationals": dict(name="Knoxville 360 Nationals", discipline="sprint_car", src=("table", "Knoxville Nationals", r"360 Knoxville Nationals Champions$", r"driver"),
                                    track="Knoxville Raceway"),
    "knoxville_late_model_nationals": dict(name="Knoxville Late Model Nationals", discipline="dirt_late_model", src=("table", "Knoxville Nationals", r"Late Model Knoxville Nationals champions$", r"driver"),
                                           track="Knoxville Raceway"),
    "kings_royal": dict(name="Kings Royal", discipline="sprint_car", src=("table", "Kings Royal", r"Winners", r"driver"),
                        track="Eldora Speedway"),
    "historical_big_one": dict(name="Historical Big One", discipline="sprint_car", src=("list", "Eldora Speedway", r"Historical Big One"),
                               track="Eldora Speedway"),
    "world_100": dict(name="World 100", discipline="dirt_late_model", src=("list", "World 100", r"^Winners$"),
                      track="Eldora Speedway"),
    "dirt_late_model_dream": dict(name="Dirt Late Model Dream", discipline="dirt_late_model", src=("list", "Eldora Speedway", r"^Dirt Late Model Dream$"),
                                  track="Eldora Speedway"),
    "prelude_to_the_dream": dict(name="Prelude to the Dream", discipline="dirt_late_model", src=("table", "Prelude to the Dream", r"Past winners", r"driver"),
                                 track="Eldora Speedway"),
    "chili_bowl": dict(name="Chili Bowl Nationals", discipline="midget", src=("list", "Chili Bowl Nationals", r"A-Main Winners"),
                       track="Tulsa Expo Center"),
    "turkey_night_grand_prix": dict(name="Turkey Night Grand Prix", discipline="midget", src=("table", "Turkey Night Grand Prix", r"List of winners", r"driver"),
                                    track=None),
    "hoosier_hundred": dict(name="Hoosier Hundred", discipline="silver_crown", src=("table", "Hoosier Hundred", r"Race results / Hoosier Hundred$", r"driver"),
                            track=None),
    "hulman_hundred": dict(name="Hulman Hundred", discipline="silver_crown", src=("table", "Hoosier Hundred", r"Race results / Hulman Hundred$", r"driver"),
                           track=None),
    "hut_hundred": dict(name="Hut Hundred", discipline="midget", src=("list", "Terre Haute Action Track", r"^Hut Hundred$"),
                        track="Terre Haute Action Track"),
    "hulman_classic": dict(name="Tony Hulman Classic", discipline="sprint_car", src=("table", "Terre Haute Action Track", r"Hulman Classic", r"driver"),
                           track="Terre Haute Action Track"),
    "sumar_classic": dict(name="Sumar Classic", discipline="silver_crown", src=("list", "Terre Haute Action Track", r"^Sumar Classic$"),
                          track="Terre Haute Action Track"),
    "super_dirt_week": dict(name="Super DIRT Week (Big-Block Modified)", discipline="dirt_modified", src=("table", "Super Dirt Week", r"List of winners", r"modified"),
                            track=None),
    "super_dirt_week_358": dict(name="Super DIRT Week (358 Modified)", discipline="dirt_modified", src=("table", "Super Dirt Week", r"List of winners", r"358 modified"),
                                track=None),
    "herald_review_100": dict(name="Herald & Review 100", discipline="dirt_late_model", src=("table", "Herald & Review 100", r"Champions", r"winner"),
                              track="Macon Speedway"),
    "harris_clash": dict(name="Harris Clash", discipline="dirt_modified", src=("list", "Harris Clash", r"Harris Clash Winners"),
                         track=None),
    "lernerville_silver_cup": dict(name="Don Martin Memorial Silver Cup", discipline="sprint_car", src=("list", "Lernerville Speedway", r"Don Martin Memorial Silver Cup"),
                                   track="Lernerville Speedway"),
    "commonwealth_clash": dict(name="Commonwealth Clash", discipline="sprint_car", src=("list", "Lernerville Speedway", r"Commonwealth Clash"),
                               track="Lernerville Speedway"),
    "lernerville_firecracker_100": dict(name="Firecracker 100", discipline="dirt_late_model", src=("list", "Lernerville Speedway", r"^Past winners$", 0),
                                        track="Lernerville Speedway"),
    "tuscarora_50": dict(name="Tuscarora 50", discipline="sprint_car", src=("table", "Port Royal Speedway", r"Tuscarora 50 winners", r"driver"),
                         track="Port Royal Speedway"),
    "utica_rome_new_yorker": dict(name="The New Yorker", discipline="dirt_modified", src=("table", "Utica-Rome Speedway", r"New Yorker", r"winner"),
                                  track="Utica-Rome Speedway"),
    "ohsweken_woo_showdown": dict(name="World of Outlaws Showdown at Ohsweken", discipline="sprint_car", src=("table", "Ohsweken Speedway", r"Showdown", r"driver"),
                                  track="Ohsweken Speedway"),
}

DISC_TO_VENUE = {"sprint_car": "sprint_car", "silver_crown": "sprint_car", "midget": "midget",
                 "dirt_late_model": "dirt_late_model", "dirt_modified": "modified"}
